### ISSUE TITLE
Add new dependent project to README

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [iMrDJAi/markdown-it-reddit-spoiler#1]
I developed a Visual Studio Code [extension](https://github.com/AbhijeetKrishnan/vscode-markdown-reddit-spoiler) to enable using Reddit spoiler tags in the in-built Markdown Preview that uses this project. I would love it if you could mention it in the README as a dependent project.

**Comment by iMrDJAi** [comment]
> I developed a Visual Studio Code [extension](https://github.com/AbhijeetKrishnan/vscode-markdown-reddit-spoiler) to enable using Reddit spoiler tags in the in-built Markdown Preview that uses this project. I would love it if you could mention it in the README as a dependent project.

@AbhijeetKrishnan Sure!
Sorry for the late reply.
